// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CombineEditionsController from "./combine_editions_controller.js"
application.register("combine-editions", CombineEditionsController)

import ImagePreviewController from "./image_preview_controller.js"
application.register("image-preview", ImagePreviewController)
