require: rubocop-performance
AllCops:
  TargetRubyVersion: 3.1
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/vendor/**/.*'
    - '**/node_modules/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    # Additional exclude files by rubocop-rails_config
    - 'db/migrate/**/*.rb'
    - 'db/*.rb'

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: true

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'actionview/test/**/*.builder'
    - 'actionview/test/**/*.ruby'
    - 'actionpack/test/**/*.builder'
    - 'actionpack/test/**/*.ruby'
    - 'activestorage/db/migrate/**/*.rb'

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Semicolon:
  AllowAsExpressionSeparator: true
