language: ruby
cache:
    bundler: true
    directories:
        - vendor/assets/bower_components
        - node_modules
rvm:
    - 2.4.4
bundler_args: --without production
addons:
      postgresql: "9.3"
services:
      - elasticsearch
before_install:
    - gem update --system
    - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.6.deb && sudo service elasticsearch restart
before_script:
    - sleep 10
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp config/database.yml.travis config/database.yml
    - npm install -g bower
    - bower install
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
