source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'koala'
gem 'omniauth-google-oauth2'
gem 'acts_as_follower'
gem 'pg'
gem 'pundit'
gem 'annotate'
gem 'active_link_to'
gem 'gretel'
gem 'paperclip'
gem 'aws-sdk', '~> 1.6'
gem 'github-markdown'
gem 'will_paginate-bootstrap'
gem 'chewy'
gem 'friendly_id', '~> 5.1.0'
gem 'babosa'
gem 'nokogiri'
gem 'exception_notification'
gem 'sitemap_generator'
gem 'fog'
gem 'figaro'
gem 'addressable'
gem 'responders', '~> 2.0'
gem 'active_record_union'
gem 'puma'
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'pry'
  gem 'pry-byebug'
end
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
  gem 'web-console', '~> 3.0'
  gem 'spring'
end
group :production do
  gem 'rails_12factor'
end
group :test do
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
  gem 'codeclimate-test-reporter', require: nil
  gem 'timecop'
end
